# Spring Application
spring.application.name=careerhub-backend

# MySQL DataSource
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=${REDIS_TIMEOUT}
spring.autoconfigure.exclude=org.springframework.boot.data.redis.autoconfigure.DataRedisRepositoriesAutoConfiguration

# Server
server.port=8000


# JWT Application Properties
app.jwt.secret=${JWT_SECRET}
app.jwt.aws-access-token-expiration-minutes=2
app.jwt.access-token-expiration-minutes=60
app.jwt.refresh-token-expiration-days=7

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Kafka Producer
spring.kafka.template.default-topic=careerhub
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Kafka Consumer
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.chrion.careerhub.*

# AWS S3
aws.s3.files-bucket-name=${AWS_S3_FILES_BUCKET}
aws.s3.watermark-files-bucket-name=${AWS_S3_WATERMARK_FILES_BUCKET}
aws.s3.profiles-bucket-name=${AWS_S3_PROFILES_BUCKET}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.s3.get-object-duration.minutes=10
aws.s3.put-object-duration.minutes=60
aws.cloud-front.url=${AWS_CLOUD_FRONT_URL}
aws.secret=${AWS_SECRET}
aws.hashing.algorithm=${AWS_HASHING_ALGORITHM}

# AWS SES
aws.ses.region=${AWS_REGION:ap-south-1}
aws.ses.from-email=${AWS_SES_FROM_EMAIL}

# File Upload

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

spring.threads.virtual.enabled=true

# ADMIN CRED
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
endpoint.health.probes.enabled=true
endpoint.health.probes.show-details=when_authorized
info.env.enabled=true
